version: 2.1

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester

    steps:
      - checkout

      - run:
          name: "Setup virtual env and install tap-listrak"
          command: |
            python3 -m venv /usr/local/share/virtualenvs/tap-listrak
            source /usr/local/share/virtualenvs/tap-listrak/bin/activate
            pip install -U "pip==22.2.2" "setuptools==65.3.0"
            pip install -e .[dev]

      - run:
          name: "Run Pylint"
          command: |
            source /usr/local/share/virtualenvs/tap-listrak/bin/activate
            pip install pylint
            pylint tap_listrak -d C,R,W || true

      - run:
          name: "Run Unit Tests with Pytest"
          command: |
            source /usr/local/share/virtualenvs/tap-listrak/bin/activate
            pip install pytest coverage
            pip install opentelemetry-api opentelemetry-sdk

            mkdir -p test_output
            pytest --cov=tap_listrak --cov-report html:htmlcov --junitxml=test_output/report.xml tests/unittests/

      - store_test_results:
          path: test_output

      - store_artifacts:
          path: htmlcov

workflows:
  version: 2

  commit:
    jobs:
      - build:
          context: circleci-user

  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
